### ISSUE TITLE
Wish that pdfoutline could clean the old outline before adding new outline

### ISSUE THREAD

**Issue by TD-Sky** [yutayamamoto/pdfoutline#4]
Sometimes I' m not satisfied with the book whose outline is messy or lacking of some parts, then I would clean this outline (in a inconvenient way) and build a new one.

If you could adopt my advice, I would be appreciated to it. Thanks !

**Comment by yutayamamoto** [comment]
Sorry, but it seems that clearing the existing outlines requires a bit of work since `pdfmark` has no such feature (as far as I can tell from [the manual](https://opensource.adobe.com/dc-acrobat-sdk-docs/acrobatsdk/pdfs/acrobatsdk_pdfmark.pdf
)).

Any PRs will be appreciated. Thank you for the comment!

**Comment by TD-Sky** [comment]
`pymupdf` has this feature, I wrapped it as a command line tool.
